//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net1711_231_ASM3_SE172092_NGUYENHOANGSON.MVCWebApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingRequests", ReplyAction="http://tempuri.org/IService1/GetBookingRequestsResponse")]
        Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest[] GetBookingRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingRequests", ReplyAction="http://tempuri.org/IService1/GetBookingRequestsResponse")]
        System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest[]> GetBookingRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTravels", ReplyAction="http://tempuri.org/IService1/GetTravelsResponse")]
        Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.Travel[] GetTravels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTravels", ReplyAction="http://tempuri.org/IService1/GetTravelsResponse")]
        System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.Travel[]> GetTravelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.User[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.User[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrUpdateBookingRequest", ReplyAction="http://tempuri.org/IService1/CreateOrUpdateBookingRequestResponse")]
        bool CreateOrUpdateBookingRequest(Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest bookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateOrUpdateBookingRequest", ReplyAction="http://tempuri.org/IService1/CreateOrUpdateBookingRequestResponse")]
        System.Threading.Tasks.Task<bool> CreateOrUpdateBookingRequestAsync(Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest bookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBookingRequest", ReplyAction="http://tempuri.org/IService1/DeleteBookingRequestResponse")]
        bool DeleteBookingRequest(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBookingRequest", ReplyAction="http://tempuri.org/IService1/DeleteBookingRequestResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookingRequestAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingRequestById", ReplyAction="http://tempuri.org/IService1/GetBookingRequestByIdResponse")]
        Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest GetBookingRequestById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookingRequestById", ReplyAction="http://tempuri.org/IService1/GetBookingRequestByIdResponse")]
        System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest> GetBookingRequestByIdAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Net1711_231_ASM3_SE172092_NGUYENHOANGSON.MVCWebApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.MVCWebApp.ServiceReference1.IService1>, Net1711_231_ASM3_SE172092_NGUYENHOANGSON.MVCWebApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest[] GetBookingRequests() {
            return base.Channel.GetBookingRequests();
        }
        
        public System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest[]> GetBookingRequestsAsync() {
            return base.Channel.GetBookingRequestsAsync();
        }
        
        public Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.Travel[] GetTravels() {
            return base.Channel.GetTravels();
        }
        
        public System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.Travel[]> GetTravelsAsync() {
            return base.Channel.GetTravelsAsync();
        }
        
        public Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.User[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.User[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public bool CreateOrUpdateBookingRequest(Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest bookingRequest) {
            return base.Channel.CreateOrUpdateBookingRequest(bookingRequest);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrUpdateBookingRequestAsync(Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest bookingRequest) {
            return base.Channel.CreateOrUpdateBookingRequestAsync(bookingRequest);
        }
        
        public bool DeleteBookingRequest(System.Guid id) {
            return base.Channel.DeleteBookingRequest(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookingRequestAsync(System.Guid id) {
            return base.Channel.DeleteBookingRequestAsync(id);
        }
        
        public Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest GetBookingRequestById(System.Guid id) {
            return base.Channel.GetBookingRequestById(id);
        }
        
        public System.Threading.Tasks.Task<Net1711_231_ASM3_SE172092_NGUYENHOANGSON.Service.BookingRequest> GetBookingRequestByIdAsync(System.Guid id) {
            return base.Channel.GetBookingRequestByIdAsync(id);
        }
    }
}
